# Generated by Django 4.1.3 on 2022-11-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateway", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateway",
            name="timestamp",
            field=models.CharField(max_length=100),
        ),
    ]
